listen_address: localhost:8080
cert_file: ./server.crt
key_file: ./server.key

errorFilePath: "D:\\Users\\selah\\Documents\\GitHub\\AutoOrder-Backend\\pkg\\errors\\errors_en.json"
# this section will be used for Token Authorization
api:
  domain: http://localhost:3000
  signing_secret: "your-super-secret"

database:
    addr: 127.0.0.1:3306
    username: root
    password: autoOrderCENG415
    db_name: autoOrder
