listen_address: 0.0.0.0:8080
cert_file: ./server.crt
key_file: ./server.key

errorFilePath: "./pkg/errors/errors_en.json"
# this section will be used for Token Authorization
api:
  domain: http://localhost:3000
  signing_secret: "your-super-secret"
  imagePath: "./pkg/images/"
  enum:
    front: [{"name":"Egg","type":"front","size":"2X"},{"name":"Cheese","type":"front","size":"2X"},{"name":"Chocolate","type":"front","size":"1X"},{"name":"Olive","type":"front","size":"1X"},{"name":"Baby Food","type":"front","size":"2X"},{"name":"Tomato Paste","type":"front","size":"1X"}]
    back: [{"name":"Milk","type":"back","size":"2X"},{"name":"Juice","type":"back","size":"2X"},{"name":"Yoghurt","type":"back","size":"3X"},{"name":"Jam","type":"back","size":"2X"},{"name":"Buttermilk","type":"back","size":"1X"}]
  python_backend_address: "https://calm-analogy-350913.lm.r.appspot.com/analyse"
  fake_api_address: "http://foodorder-env.eba-jkyejwja.us-east-1.elasticbeanstalk.com/orders/order"
database:
    addr: 127.0.0.1:3306
    username: root
    password: autoOrder
    db_name: autoOrder