listen_address: 0.0.0.0:8080
cert_file: ./server.crt
key_file: ./server.key

errorFilePath: "./pkg/errors/errors_en.json"
# this section will be used for Token Authorization
api:
  domain: http://localhost:3000
  signing_secret: "your-super-secret"
  imagePath: "./pkg/images/"
  enum:
    front: ["elma","armut"]
    back: ["Süt","Yoğurt"]

database:
    addr: 127.0.0.1:3306
    username: root
    password: autoOrder
    db_name: autoOrder